### ISSUE TITLE
Add Analytics Tracking for Events

### ISSUE THREAD

**Issue by dhochbaum-dcp** [NYCPlanning/ae-cp-map#110]
Add Analytics tracking to the following events:

- [x] Filter by District accordion
- [x] District Type dropdown
- [x] Borough dropdown
- [x] District Number dropdown
- [x] Go to Selected District button
- [x] Selected District accordion
- [x] Capital Project click
- [x] Community Districts list page nav
    - [x] Prev
    - [x] Next
- [x] Capital Projects Portal accordion
- [x] Project Info Modal Close button
- [x] Commitment Details accordion

**Comment by dhochbaum-dcp** [comment]
Blocked by #38.
District Type dropdown is completed in #97, which completes #38.
